config/routes.rb
Blog::Application.routes.draw do
  match 'posts/:id' => 'posts#show', :as => :posts_show
  
  match "posts" => "posts#index", :as => :posts_index
  
  match "post/new" => "posts#new", :as => :posts_new
  match "post/create" => "posts#create", :as => :posts_create
  
  match "posts/:id/edit" => "posts#edit", :as => :posts_edit
  match "posts/:id/update" => "posts#update", :as => :posts_update

  root :to => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :post_id, :user_id
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :encrypted_password, :is_admin, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.find(:all)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]
    @post.save
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:post][:id])
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]
    @post.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
    <h1>Mi blog en RoR</h1>
</header>
<nav class="navbar">
  <div class="navbar_inner">
    <ul class="nav nav-pills">
      <li><%= link_to 'Inicio', root_path %></li>
      <li><%= link_to 'Nuevo post', posts_new_path %></li>
    </ul>
  </div>
  </ul>
</nav>
<br />
<%= yield %>
<footer>
  <p>Blog hecho con ruby on rails</p>
</footer>
</body>
</html>

app/views/posts/create.html.erb
<span class="label label-success">El artículo ha sido guardado</span>
<%= link_to "Volver al inicio", posts_show_path('') %>

app/views/posts/edit.html.erb
<h1>Editar artículo</h1>
<%= form_for @post, :url => { :action => "update" } do |f| %>  
  <%= f.label :title, "Title" %><br />
  <%= f.text_field :title, :value => @post.title %><br />
  <%= f.label :body, "Body", :value => @post.body %><br />
  <%= f.text_area :body, :size => "60x12" %><br />
  <%= f.hidden_field :id, :value => @post.id %>
  <%= f.submit "Submit" %>
<% end %>

app/views/posts/index.html.erb
<% unless @posts.empty? %>
  <ul>
  <% for post in @posts %>
     <li><%= link_to post.title, posts_show_path(post.id) %></li>
  <% end %>
  </ul>
<% else %>
  <p>¡No hay ningun articulo!</p>
  <p>Pulsa <%= link_to 'crear nuevo articulo', posts_new_path %> para crear uno.</p>
<% end %>

app/views/posts/new.html.erb
<div>
    <h3>Nuevo arículo</h3>
    <%= form_for @post, :url => { :action => "create" } do |f| %>
      <div class="field">
        <%= f.label :title, "Título" %>
        <%= f.text_field :title %><br />
      </div>
      <div class="field">
        <%= f.label :body, "Cuerpo" %><br />
        <%= f.text_area :body, :size => "60x12" %><br />
      </div>
      <div class="btn-group">
        <%= f.submit "Guardar" %>
      </div>
    <% end %>
</div>

app/views/posts/show.html.erb
<div>
    <h3><%= @post.title %> | <%= link_to "Editar", posts_edit_path(@post.id) %></h3>
</div>
<div class="blog_post">
  <%= @post.body %>
</div>

app/views/posts/update.html.erb
<span class="label label-success">El artículo ha sido modificado</span>
<p><%= link_to "Ver el artículo", posts_show_path(@post.id) %></p>